### ISSUE TITLE
Make the map border of filter less thick

### ISSUE THREAD

**Issue by R3rumCC** [giuseppelazzara98/polito-se2-22-18-HT#17]

**Comment by Francesco-rosati** [comment]
The issue can be considered closed, in fact, now he map has a less pronounced appearance and the contours are still defined but without the background.

![Schermata 2022-12-21 alle 13 54 33](https://user-images.githubusercontent.com/80273021/208910266-db11413a-dffe-4469-968d-857e48aa7b13.png)
